[Package]
name = "alacritty"
description = "Alacritty terminal"
repo = { host = "github", owner = "mkanilsson-dotfiles", repo = "alacritty" }
install-path = "$HOME/.config/alacritty"

dependencies = []
