[Package]
name = "dunst"
description = "Gruvbox themed minimalistic dunst"
repo = { host = "github", owner = "mkanilsson-dotfiles", repo = "dunst" }
install-path = "$HOME/.config/dunst"

dependencies = []
