[Package]
name = "fish"
description = "fish with custom prompt and vi bindings"
repo = { host = "github", owner = "mkanilsson-dotfiles", repo = "fish" }
install-path = "$HOME/.config/fish"

dependencies = []
