[Package]
name = "hyprland"
description = "Gruvbox themed hyprland configuration with blue accent color"
repo = { host = "github", owner = "mkanilsson-dotfiles", repo = "hypr" }
install-path = "$HOME/.config/hypr"

dependencies = [
    "scripts",
    "alacritty",
    "rofi",
    "swaync",
    "wallpapers",
    "waybar",
]
