[Package]
name = "polybar"
description = "Gruvbox themed polybar"
repo = { host = "github", owner = "mkanilsson-dotfiles", repo = "polybar" }
install-path = "$HOME/.config/polybar"

dependencies = []
